name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Imprimir variable de entorno
        run: |
          DOCKER_USERNAME="aaroncane"
          DOCKERHUB_TOKEN="dckr_pat_gH4mLtgQ3_yZ7hCoUfi9gln_hbs"
          echo "El valor de DOCKER_USERNAME es: $DOCKER_USERNAME"
          echo "El valor de DOCKERHUB_TOKEN es: $DOCKERHUB_TOKEN"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: $DOCKER_USERNAME
          password: "dckr_pat_gH4mLtgQ3_yZ7hCoUfi9gln_hbs"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
